export const INDONESIA_CITIES = [
  'Ambon',
  'Balikpapan',
  'Bandar Lampung',
  'Bandung',
  'Banjarmasin',
  'Batam',
  'Bekasi',
  'Bengkulu',
  'Bogor',
  'Cilegon',
  'Cimahi',
  'Denpasar',
  'Depok',
  'Gorontalo',
  'Jakarta Barat',
  'Jakarta Pusat',
  'Jakarta Selatan',
  'Jakarta Timur',
  'Jakarta Utara',
  'Jambi',
  'Jayapura',
  'Kediri',
  'Kendari',
  'Kupang',
  'Makassar',
  'Malang',
  'Manado',
  'Mataram',
  'Medan',
  'Padang',
  'Palangka Raya',
  'Palembang',
  'Palu',
  'Pekanbaru',
  'Pontianak',
  'Prabumulih',
  'Samarinda',
  'Semarang',
  'Serang',
  'Sorong',
  'Sukabumi',
  'Surabaya',
  'Surakarta',
  'Tangerang',
  'Tangerang Selatan',
  'Tasikmalaya',
  'Ternate',
  'Yogyakarta',
] as const;
